import type { PropertyFacts } from "@/types/listing-studio";
import type { ListingStudioAgentProfile } from "@/lib/profiles/effective-profile";
import { googleFontsLinkFor } from "@/lib/fonts/google-fonts";

// ============================================================
// Just-Listed HTML email template.
//
// Two variants:
//   - "announcement" : clean Just-Listed format
//   - "pricing"      : adds a "Why this price" block sourced from the CMA
//
// The template emits inline-styled HTML as a string. React-DOM-to-string
// produces output that breaks in Outlook + many ESP code editors — inline
// styles in a hand-written template are the email-industry default for a
// reason.
//
// The agent provides hosted image URLs themselves (they upload to their
// ESP's media library) — we never host listing photos.
// ============================================================

export type HtmlEmailVariant = "announcement" | "pricing";

export interface CmaSummary {
  recommendedPriceCents: number;
  /** One-liner positioning sentence: "priced below 3 of 5 recent comps in {neighborhood}". */
  compPositioning: string;
  /** One-liner market-trend statement: "Median sale price up 4% YoY in {zip}". */
  marketTrendLine: string;
}

export interface RenderJustListedInput {
  facts: PropertyFacts;
  listingAddress: string;
  agentProfile: ListingStudioAgentProfile;
  variant: HtmlEmailVariant;
  /** Copy generated by the LLM via getHtmlEmailCopyPrompt. */
  copy: {
    subject: string;
    headline: string;
    body: string;
    cta_label: string;
  };
  /** Required for variant='pricing'. Renderer ignores when present on 'announcement'. */
  cmaSummary?: CmaSummary;
  /** Optional hosted hero image URL (agent provides after uploading to their ESP). */
  heroImageUrl?: string | null;
  /** Optional CTA URL the agent supplies — defaults to the website on the profile. */
  ctaUrl?: string | null;
}

/**
 * Render the inline-styled Just-Listed email. Pure string concat — safe to
 * paste into any ESP code editor.
 */
export function renderJustListedHtml(input: RenderJustListedInput): string {
  const { facts, listingAddress, agentProfile: p, variant, copy } = input;

  const heading_font = p.heading_font || "Inter, sans-serif";
  const body_font = p.body_font || "Inter, sans-serif";
  const primary = p.primary_color;
  const accent = p.accent_color;

  const headerBg =
    p.header_treatment === "gradient"
      ? `linear-gradient(135deg, ${primary}, ${p.secondary_color})`
      : primary;

  const ctaUrl =
    (input.ctaUrl && input.ctaUrl.trim()) ||
    p.website_url ||
    "https://example.com";

  const heroBlock = input.heroImageUrl
    ? `
      <tr>
        <td style="padding:0;font-size:0;line-height:0;">
          <img src="${escapeAttr(input.heroImageUrl)}" alt="${escapeAttr(listingAddress)}" width="600" style="display:block;width:100%;height:auto;max-width:600px;border:0;outline:none;" />
        </td>
      </tr>`
    : `
      <tr>
        <td style="padding:0;">
          <div style="background:#f1f1f1;color:#999;font-family:${body_font};font-size:13px;text-align:center;padding:80px 24px;border-bottom:1px solid #e5e5e5;">
            [ Paste your hosted hero image URL into the &lt;img src&gt; before sending ]
          </div>
        </td>
      </tr>`;

  const factsTable = renderFactsTable(facts, accent, body_font);

  const pricingBlock =
    variant === "pricing" && input.cmaSummary
      ? renderPricingBlock(input.cmaSummary, primary, accent, body_font, heading_font)
      : "";

  const headshotBlock = p.headshot_url
    ? `<img src="${escapeAttr(p.headshot_url)}" alt="${escapeAttr(p.full_name || "Agent")}" width="56" height="56" style="display:block;width:56px;height:56px;border-radius:50%;object-fit:cover;border:0;" />`
    : "";

  const signatureBlock = `
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-top:24px;border-top:1px solid #eee;padding-top:16px;">
      <tr>
        ${headshotBlock ? `<td valign="top" width="64" style="padding-right:12px;">${headshotBlock}</td>` : ""}
        <td valign="top" style="font-family:${body_font};font-size:13px;line-height:1.5;color:#333;">
          <p style="margin:0;font-weight:600;color:#1a1a1a;">${escapeHtml(p.full_name || "")}</p>
          ${p.title ? `<p style="margin:0;color:#666;">${escapeHtml(p.title)}</p>` : ""}
          ${p.brokerage ? `<p style="margin:0;color:#666;">${escapeHtml(p.brokerage)}</p>` : ""}
          ${p.phone ? `<p style="margin:6px 0 0;">${escapeHtml(p.phone)}</p>` : ""}
          ${p.reply_to_email ? `<p style="margin:0;"><a href="mailto:${escapeAttr(p.reply_to_email)}" style="color:${primary};text-decoration:none;">${escapeHtml(p.reply_to_email)}</a></p>` : ""}
        </td>
      </tr>
    </table>
  `;

  const complianceParts: string[] = [];
  if (p.license_number) {
    const reg = p.regulatory_body ? ` · ${escapeHtml(p.regulatory_body)}` : "";
    complianceParts.push(`License #${escapeHtml(p.license_number)}${reg}`);
  }
  if (p.brokerage && !p.license_number) {
    complianceParts.push(escapeHtml(p.brokerage));
  }
  if (p.license_info) complianceParts.push(escapeHtml(p.license_info));
  const equalHousing = `Equal Housing Opportunity ⌂`;
  complianceParts.push(equalHousing);

  const disclaimer = p.legal_disclaimer && p.legal_disclaimer.trim()
    ? `<p style="margin:6px 0 0;font-style:italic;">${escapeHtml(p.legal_disclaimer)}</p>`
    : "";

  const complianceBlock = `
    <div style="margin-top:24px;padding-top:12px;border-top:1px solid #eee;font-family:${body_font};font-size:11px;color:#888;line-height:1.5;">
      <p style="margin:0;">${complianceParts.join(" · ")}</p>
      ${disclaimer}
    </div>
  `;

  const fontsLink = googleFontsLinkFor(heading_font, body_font);
  const fontsHead = fontsLink
    ? `<link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link rel="stylesheet" href="${fontsLink}" />`
    : "";

  // CTA button shape adapts to the user's chosen button_shape via border-radius.
  const ctaButton = `
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;">
      <tr>
        <td style="background:${accent};border-radius:6px;">
          <a href="${escapeAttr(ctaUrl)}" style="display:inline-block;padding:14px 28px;font-family:${heading_font};font-size:15px;font-weight:600;color:#ffffff;text-decoration:none;letter-spacing:0.2px;">${escapeHtml(copy.cta_label || "View listing details")}</a>
        </td>
      </tr>
    </table>
  `;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(copy.subject)}</title>
  ${fontsHead}
</head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:${body_font};color:#1a1a1a;">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f5f5f5;">
    <tr>
      <td align="center" style="padding:24px 12px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.05);">
          <!-- Header -->
          <tr>
            <td style="background:${headerBg};padding:24px;color:#ffffff;">
              ${p.logo_url ? `<img src="${escapeAttr(p.logo_url)}" alt="Logo" style="max-height:36px;display:block;margin-bottom:12px;" />` : ""}
              <p style="margin:0;font-family:${heading_font};font-size:12px;letter-spacing:1.5px;text-transform:uppercase;color:rgba(255,255,255,0.85);">Just Listed</p>
              <h1 style="margin:8px 0 0;font-family:${heading_font};font-size:24px;font-weight:700;line-height:1.25;">${escapeHtml(listingAddress)}</h1>
              ${facts.city || facts.state ? `<p style="margin:6px 0 0;color:rgba(255,255,255,0.85);font-size:13px;">${escapeHtml([facts.city, facts.state, facts.zip].filter(Boolean).join(", "))}</p>` : ""}
            </td>
          </tr>
          ${heroBlock}
          <!-- Body -->
          <tr>
            <td style="padding:24px;font-family:${body_font};font-size:15px;line-height:1.65;color:#1a1a1a;">
              <h2 style="margin:0 0 12px;font-family:${heading_font};color:${primary};font-size:20px;font-weight:700;">${escapeHtml(copy.headline)}</h2>
              <p style="margin:0 0 16px;">${escapeHtml(copy.body)}</p>
              ${factsTable}
              ${pricingBlock}
              ${ctaButton}
              ${signatureBlock}
              ${complianceBlock}
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function renderFactsTable(
  facts: PropertyFacts,
  accent: string,
  body_font: string,
): string {
  const cells: { label: string; value: string }[] = [];
  if (facts.beds != null) cells.push({ label: "Beds", value: String(facts.beds) });
  if (facts.baths != null) cells.push({ label: "Baths", value: String(facts.baths) });
  if (facts.living_area_sqft != null)
    cells.push({
      label: "Sq Ft",
      value: facts.living_area_sqft.toLocaleString(),
    });
  if (facts.lot_area_sqft != null)
    cells.push({
      label: "Lot",
      value: `${facts.lot_area_sqft.toLocaleString()} sqft`,
    });
  if (cells.length === 0) return "";

  const cellHtml = cells
    .map(
      (c) => `
        <td style="padding:12px;text-align:center;border:1px solid #eee;background:#fafafa;">
          <p style="margin:0;color:#888;font-family:${body_font};font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">${escapeHtml(c.label)}</p>
          <p style="margin:4px 0 0;color:${accent};font-family:${body_font};font-size:18px;font-weight:700;">${escapeHtml(c.value)}</p>
        </td>`,
    )
    .join("");

  return `
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;margin:20px 0;">
      <tr>${cellHtml}</tr>
    </table>
  `;
}

function renderPricingBlock(
  cma: CmaSummary,
  primary: string,
  accent: string,
  body_font: string,
  heading_font: string,
): string {
  const priceDollars = (cma.recommendedPriceCents / 100).toLocaleString(
    "en-US",
    { style: "currency", currency: "USD", maximumFractionDigits: 0 },
  );
  return `
    <div style="margin:24px 0;padding:20px;background:linear-gradient(135deg, ${primary}10, ${accent}10);border-left:4px solid ${accent};border-radius:6px;">
      <p style="margin:0;font-family:${body_font};font-size:11px;text-transform:uppercase;letter-spacing:1.2px;color:${primary};font-weight:700;">Why this price</p>
      <p style="margin:8px 0 0;font-family:${heading_font};font-size:28px;font-weight:700;color:${primary};">${escapeHtml(priceDollars)}</p>
      <p style="margin:8px 0 0;font-family:${body_font};font-size:14px;line-height:1.55;color:#333;">${escapeHtml(cma.compPositioning)}</p>
      <p style="margin:6px 0 0;font-family:${body_font};font-size:13px;line-height:1.55;color:#666;">${escapeHtml(cma.marketTrendLine)}</p>
    </div>
  `;
}

function escapeHtml(s: string): string {
  if (s == null) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}
